version: '3.8'

networks:
  nginx-php815-mysql:
services:
  #nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
      - /var/www/html/app/vendor
    depends_on:
      - php815-service
      - mysql8-service
    networks:
      - nginx-php815-mysql
  #php
  php815-service:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: php815-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project:cached
      - /var/www/html/app/vendor
    networks:
      - nginx-php815-mysql
  #mySQL
  mysql8-service:
    image: mysql:8
    container_name: mysql-container
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql:cached
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
    networks:
      - nginx-php815-mysql
